---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: kibana-oss
  labels:
    kubeaddons.mesosphere.io/name: kibana-oss
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "7.9.3-1"
    appversion.kubeaddons.mesosphere.io/kibana-oss: "7.9.3"
    docs.kubeaddons.mesosphere.io/kibana-oss: "https://www.elastic.co/guide/en/kibana/7.9/index.html"
    values.chart.helm.kubeaddons.mesosphere.io/kibana-oss: "https://raw.githubusercontent.com/elastic/helm-charts/7.9.3/kibana/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: docker
      enabled: false
    - name: none
      enabled: true
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: elasticsearch-oss
  chartReference:
    chart: kibana
    repo: https://helm.elastic.co
    version: 7.9.3
    values: |
      ---
      image: "docker.elastic.co/kibana/kibana-oss"
      imageTag: "7.9.3"
      elasticsearchHosts: "http://elasticsearch-oss-client:9200"
