---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: elasticsearch-oss
  labels:
    kubeaddons.mesosphere.io/name: elasticsearch-oss
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "7.10.0-1"
    appversion.kubeaddons.mesosphere.io/elasticsearch-oss: "7.10.0"
    docs.kubeaddons.mesosphere.io/elasticsearch-oss: "https://www.elastic.co/guide/en/elasticsearch/reference/7.10/index.html"
    # TODO@kjoshi: Change this to reference a tag!
    values.chart.helm.kubeaddons.mesosphere.io/elasticsearch-oss: "https://raw.githubusercontent.com/kaiwalyajoshi/kommander-elasticsearch/kjoshi/elastic-7.10.x/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: docker
      enabled: false
    - name: none
      enabled: true
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/provides: storageclass
  chartReference:
    chart: kommander-elasticsearch
    repo: https://kaiwalyajoshi.github.io/kommander-elasticsearch
    version: 0.2.1
    values: |
      ---
      elasticsearch-client:
        clusterName: "elasticsearch-oss"
        nodeGroup: "client"
        masterService: "elasticsearch-oss-master"
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        volumeClaimTemplate:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 1Gi
      elasticsearch-master:
        clusterName: "elasticsearch-oss"
        nodeGroup: "master"
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        volumeClaimTemplate:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 2Gi
      elasticsearch-data:
        clusterName: "elasticsearch-oss"
        nodeGroup: "data"
        masterService: "elasticsearch-oss-master"
        replicas: 3
        resources:
          requests:
            cpu: "1000m"
            memory: "4Gi"
          limits:
            cpu: "1000m"
            memory: "4Gi"
        volumeClaimTemplate:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 10Gi
      elasticsearch-ingest:
        clusterName: "elasticsearch-oss"
        nodeGroup: "ingest"
        masterService: "elasticsearch-oss-master"
        replicas: 0 #Disabled
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        volumeClaimTemplate:
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 2Gi
