---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: elasticsearch_oss
  labels:
    kubeaddons.mesosphere.io/name: elasticsearch_oss
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "7.9.3-1"
    appversion.kubeaddons.mesosphere.io/elasticsearch_oss: "7.9.3"
    docs.kubeaddons.mesosphere.io/elasticsearch_oss: "https://www.elastic.co/guide/en/elasticsearch/reference/7.9/index.html"
    # TODO@kjoshi: Change this to reference a tag!
    values.chart.helm.kubeaddons.mesosphere.io/elasticsearch_oss: "https://raw.githubusercontent.com/kaiwalyajoshi/kommander-elasticsearch/kjoshi/elastic-7.9.3/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: docker
      enabled: false
    - name: none
      enabled: true
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/provides: storageclass
  chartReference:
    chart: kommander-elasticsearch
    repo: https://kaiwalyajoshi.github.io/kommander-elasticsearch
    version: 0.1.0
    values: |
      ---
      elasticsearch-client:
        clusterName: "elasticsearch-oss"
        nodeGroup: "client"
        masterService: "elasticsearch-oss-master"
      elasticsearch-master:
        clusterName: "elasticsearch-oss"
        nodeGroup: "master"
      elasticsearch-data:
        clusterName: "elasticsearch-oss"
        nodeGroup: "data"
        masterService: "elasticsearch-oss-master"
      elasticsearch-ingest:
        clusterName: "elasticsearch-oss"
        nodeGroup: "ingest"
        masterService: "elasticsearch-oss-master"
